<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertModel\Entity\AdvertEntity;

$addLink = $this->url(
    'advert-backend/modify', ['action' => 'add'], true
);

$this->headTitle('advert_backend_title_display_index');
$this->h1('advert_backend_h1_display_index');
?>
<table class="table table-condensed table-bordered table-striped">
  <thead>
  <tr>
    <th><?= $this->translate('advert_backend_label_type') ?></th>
    <th><?= $this->translate('advert_backend_label_status') ?></th>
    <th><?= $this->translate('advert_backend_label_title') ?></th>
    <th class="hidden-xs">
      <?= $this->translate('advert_backend_label_company') ?>
    </th>
    <th class="hidden-xs">
      <?= $this->translate('advert_backend_label_location') ?>
    </th>
    <th class="hidden-xs">
      <?= $this->translate('advert_backend_label_updated') ?>
    </th>
    <th class="text-center">
      <a href="<?= $addLink ?>"><i class="fa fa-plus-square-o"></i></a>
    </th>
  </tr>
  </thead>
  <tbody>
  <?php /** @var AdvertEntity $advert */ ?>
  <?php foreach ($this->advertList as $advert) : ?>
    <?php
    $showLink    = $this->url(
        'advert-backend/show', ['id' => $advert->getId()], true
    );
    $editLink    = $this->url(
        'advert-backend/modify',
        ['action' => 'edit', 'id' => $advert->getId()], true
    );
    $deleteLink  = $this->url(
        'advert-backend/modify',
        ['action' => 'delete', 'id' => $advert->getId()], true
    );
    $approveLink = $this->url(
        'advert-backend/modify',
        ['action' => 'approve', 'id' => $advert->getId()], true
    );
    $blockLink   = $this->url(
        'advert-backend/modify',
        ['action' => 'block', 'id' => $advert->getId()], true
    );
    ?>
    <tr>
      <td>
        <?= $this->translate('advert_model_option_type_' . $advert->getType()) ?>
      </td>
      <td>
        <?= $this->translate('advert_model_option_status_' . $advert->getStatus()) ?>
      </td>
      <td>
        <a href="<?= $showLink ?>">
          <?= $advert->getTitle() ?>
        </a>
      </td>
      <td class="hidden-xs">
        <?= $advert->getCompany()->getName() ?>
      </td>
      <td class="hidden-xs">
        <?= $advert->getLocation() ?>
      </td>
      <td class="hidden-xs">
        <?= $this->dateFormat(
            $advert->getUpdated(),
            IntlDateFormatter::LONG,
            IntlDateFormatter::MEDIUM
        ) ?>
      </td>
      <td class="text-center">
        <a href="<?= $showLink ?>" class="hidden-xs hidden-sm">
          <i class="fa fa-file-text-o"></i>
        </a>
        <a href="<?= $editLink ?>">
          <i class="fa fa-pencil"></i>
        </a>
        <a href="<?= $deleteLink ?>" class="hidden-xs hidden-sm">
          <i class="fa fa-trash-o"></i>
        </a>
        <a href="<?= $approveLink ?>" class="visible-lg-inline">
          <i class="fa fa-thumbs-o-up"></i>
        </a>
        <a href="<?= $blockLink ?>" class="visible-lg-inline">
          <i class="fa fa-thumbs-o-down"></i>
        </a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
<nav class="text-center">
  <?php
  echo $this->paginationControl(
      $this->advertList,
      'Sliding',
      'pagination/page-navigation',
      [
          'route' => 'advert-backend/page'
      ]
  );
  ?>
</nav>
