<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$addLink = $this->url(
    'advert-backend/modify', ['action' => 'add'], true
);

$this->headTitle('Annoncen administrieren');
?>
<div class="page-header">
  <h1>Annoncen administrieren</h1>
</div>

<table class="table table-condensed table-bordered table-striped">
  <thead>
  <tr>
    <th>Typ</th>
    <th>Status</th>
    <th>Titel</th>
    <th class="hidden-xs">Firma</th>
    <th class="hidden-xs">Ort</th>
    <th class="hidden-xs">Datum</th>
    <th class="text-center">
      <a href="<?= $addLink ?>"><i class="fa fa-plus-square-o"></i></a>
    </th>
  </tr>
  </thead>
  <tbody>
  <?php foreach ($this->advertList as $advert) : ?>
    <?php
    if ($advert['type'] == 'job') {
        $advertType = 'Job';
    } else {
        $advertType = 'Projekt';
    }

    $showLink    = $this->url(
        'advert-backend/show', ['id' => $advert['id']], true
    );
    $editLink    = $this->url(
        'advert-backend/modify',
        ['action' => 'edit', 'id' => $advert['id']], true
    );
    $deleteLink  = $this->url(
        'advert-backend/modify',
        ['action' => 'delete', 'id' => $advert['id']], true
    );
    $approveLink = $this->url(
        'advert-backend/modify',
        ['action' => 'approve', 'id' => $advert['id']], true
    );
    $blockLink   = $this->url(
        'advert-backend/modify',
        ['action' => 'block', 'id' => $advert['id']], true
    );
    ?>
    <tr>
      <td>
        <?= $advertType ?>
      </td>
      <td>
        <?= $advert['status'] ?>
      </td>
      <td>
        <a href="<?= $showLink ?>">
          <?= $advert['title'] ?>
        </a>
      </td>
      <td class="hidden-xs">
        <?= $advert['company']['name'] ?>
      </td>
      <td class="hidden-xs">
        <?= $advert['location'] ?>
      </td>
      <td class="hidden-xs">
        <?= $advert['updated'] ?>
      </td>
      <td class="text-center">
        <a href="<?= $showLink ?>" class="hidden-xs hidden-sm">
          <i class="fa fa-file-text-o"></i>
        </a>
        <a href="<?= $editLink ?>">
          <i class="fa fa-pencil"></i>
        </a>
        <a href="<?= $deleteLink ?>" class="hidden-xs hidden-sm">
          <i class="fa fa-trash-o"></i>
        </a>
        <a href="<?= $approveLink ?>" class="visible-lg-inline">
          <i class="fa fa-thumbs-o-up"></i>
        </a>
        <a href="<?= $blockLink ?>" class="visible-lg-inline">
          <i class="fa fa-thumbs-o-down"></i>
        </a>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
