<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$advert = $this->advert;

if ($advert['type'] == 'job') {
    $advertType = 'Job';
} else {
    $advertType = 'Projekt';
}

$listLink    = $this->url('advert-backend', [], true);
$showLink    = $this->url(
    'advert-backend/show', ['id' => $advert['id']], true
);
$editLink    = $this->url(
    'advert-backend/modify', ['action' => 'edit', 'id' => $advert['id']], true
);
$deleteLink  = $this->url(
    'advert-backend/modify', ['action' => 'delete', 'id' => $advert['id']], true
);
$approveLink = $this->url(
    'advert-backend/modify', ['action' => 'approve', 'id' => $advert['id']], true
);
$blockLink   = $this->url(
    'advert-backend/modify', ['action' => 'block', 'id' => $advert['id']], true
);

$this->headTitle('Annonce anzeigen');
?>
<div class="page-header">
  <h1>Annonce anzeigen</h1>
</div>

<p>
  <a href="<?= $showLink ?>" class="btn btn-primary">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">Anzeigen</span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-default">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">Bearbeiten</span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">Löschen</span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">Freigeben</span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">Sperren</span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="well">
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">Typ</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['type'] ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Angelegt</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['created'] ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Geändert</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['updated'] ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Status</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['status'] ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Unternehmen</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['company']['name'] ?>
        <i>
            (Ansprechpartner: <?= $advert['company']['contact'] ?>,
            E-Mail-Adresse: <?= $advert['company']['email'] ?>)
        </i>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Ort</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['location'] ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Titel</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['title'] ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Text</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert['text'] ?>
      </div>
    </div>
  </form>
</div>
