<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('application_title_error_404');
$this->h1('application_h1_error_404');

if (isset($this->reason) && $this->reason) {
    switch ($this->reason) {
        case 'error-controller-cannot-dispatch':
            $message = 'application_message_controller_not_dispatched';
            break;
        case 'error-controller-not-found':
            $message = 'application_message_controller_not_found';
            break;
        case 'error-controller-invalid':
            $message = 'application_message_controller_invalid';
            break;
        case 'error-router-no-match':
            $message = 'application_message_controller_no_match';
            break;
        default:
            $message = 'application_message_controller_other';
            break;
    }
}
?>
<div class="jumbotron">
  <h2><?= $this->translate('application_h2_error_404'); ?></h2>
  <p>
    <?= $this->translate('application_misc_reason') ?>:
    <?= $this->translate($message) ?>
  </p>
  <p class="pull-center">
    <a href="/" class="btn btn-success">
      <?= $this->translate('application_action_homepage'); ?>
    </a>
  </p>
</div>
