<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('application_title_error_index');
$this->h1('application_h1_error_index');
?>
<div class="jumbotron">
  <h2><?= $this->translate('application_h2_error_index'); ?></h2>
  <p>
    <?= $this->translate('application_message_try_later') ?>:
  </p>
  <?php var_dump($this->exception) ?>`
  <p class="pull-center">
    <a href="/" class="btn btn-success">
      <?= $this->translate('application_action_homepage'); ?>
    </a>
  </p>
</div>
