<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('Server Fehler');
?>
<div class="page-header">
    <h1>Server Fehler</h1>
</div>

<div class="jumbotron">
    <h2>Ein interner Server Fehler ist aufgetreten.</h2>
    <p>
        Bitte versuchen Sie es später noch einmal.
    </p>
    <?php var_dump($this->exception) ?>`
    <p class="pull-center">
        <a href="/" class="btn btn-success">
            Zurück zur Startseite
        </a>
    </p>
</div>
