<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use CompanyBackend\Form\CompanyFormInterface;

/** @var CompanyFormInterface $form */
$form = $this->companyForm;

$listLink = $this->url('company-backend', [], true);

$this->headTitle('Unternehmen anlegen');
$this->h1('Unternehmen anlegen');
?>
<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="well">
  <?= $this->bootstrapForm($form); ?>
</div>
