<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use CompanyBackend\Form\CompanyFormInterface;
use CompanyModel\Entity\CompanyEntity;

/** @var CompanyFormInterface $form */
$form = $this->companyForm;

/** @var CompanyEntity $company */
$company = $this->company;

$listLink    = $this->url('company-backend', [], true);
$showLink    = $this->url(
    'company-backend/show', ['id' => $company->getId()], true
);
$editLink    = $this->url(
    'company-backend/modify', ['action' => 'edit', 'id' => $company->getId()], true
);
$deleteLink  = $this->url(
    'company-backend/modify', ['action' => 'delete', 'id' => $company->getId()], true
);
$approveLink = $this->url(
    'company-backend/modify', ['action' => 'approve', 'id' => $company->getId()], true
);
$blockLink   = $this->url(
    'company-backend/modify', ['action' => 'block', 'id' => $company->getId()], true
);

$this->headTitle('Unternehmen bearbeiten');
$this->h1('Unternehmen bearbeiten');
?>
<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">Anzeigen</span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-primary">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">Bearbeiten</span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">Löschen</span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">Freigeben</span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">Sperren</span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="well" style="position: relative">
  <div style="position: absolute; right: 20px;">
    <img src="<?= $company->getLogo() ?>">
  </div>
  <div class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">Angelegt</label>
      <div class="col-sm-10 form-control-static">
        <?= $company->getRegistered()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Geändert</label>
      <div class="col-sm-10 form-control-static">
        <?= $company->getUpdated()->format('d.m.Y H:i:s')  ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Status</label>
      <div class="col-sm-10 form-control-static">
        <?= $company->getStatus() ?>
      </div>
    </div>
  </div>
  <?= $this->bootstrapForm($form); ?>
</div>
