<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/index/index' => __DIR__ . '/view/application/index/index.phtml',
    'error/index'             => __DIR__ . '/view/error/index.phtml',
    'error/404'               => __DIR__ . '/view/error/404.phtml',
    'layout/footer'           => __DIR__ . '/view/layout/footer.phtml',
    'layout/header'           => __DIR__ . '/view/layout/header.phtml',
    'layout/layout'           => __DIR__ . '/view/layout/layout.phtml',
);
