<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertModel\Entity\AdvertEntity;

/** @var AdvertEntity $advert */
$advert = $this->advert;

if ($advert->getType() == 'job') {
  $color         = 'primary';
  $advertMessage = 'advert_frontend_message_type_job';
  $listLink      = $this->url('advert-job', [], true);
  $listText      = 'advert_frontend_action_back_jobs';
} else {
  $color         = 'success';
  $advertMessage = 'advert_frontend_message_type_project';
  $listLink      = $this->url('advert-project', [], true);
  $listText      = 'advert_frontend_action_back_projects';
}

$this->headTitle($advert->getTitle());
$this->h1($advert->getTitle());
?>
<p class="text-center">
  <a class="btn btn-default" href="<?= $listLink; ?>">
    <i class="fa fa-arrow-circle-left"></i>
    <?= $this->translate($listText); ?>
  </a>
</p>
<div class="panel panel-<?= $color ?>">
  <div class="panel-heading clearfix">
    <div class="left-text">
      <strong><?= $advert->getTitle(); ?></strong>
    </div>
    <div class="right-text">
      <?= $advert->getCompany()->getName() ?>
    </div>
  </div>
  <div class="panel-body">
    <div class="col-sm-9">
      <p><?= $advert->getText(); ?></p>
    </div>
    <div class="col-sm-3 company">
      <p>
        <img class="img-responsive"
             src="<?= $advert->getCompany()->getLogo() ?>">
      </p>
      <h5>
        <strong>
          <?= $this->translate('advert_frontend_label_type_contact'); ?>
        </strong>
      </h5>
      <p><?= $advert->getCompany()->getContact() ?></p>
      <p><?= $advert->getCompany()->getEmail() ?></p>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="left-text">
      <div class="label label-<?= $color; ?>">
        <?= sprintf(
            $this->translate($advertMessage), $advert->getLocation()
        ); ?>
      </div>
    </div>
    <div class="right-text">
      <div class="label label-<?= $color; ?>">
        <?= sprintf(
            $this->translate('advert_frontend_label_last_update'),
            $this->dateFormat(
                $advert->getUpdated(),
                IntlDateFormatter::LONG,
                IntlDateFormatter::MEDIUM
            )
        ); ?>
      </div>
    </div>
  </div>
</div>
<p class="text-center">
  <a class="btn btn-default" href="<?= $listLink; ?>">
    <i class="fa fa-arrow-circle-left"></i>
    <?= $this->translate($listText); ?>
  </a>
</p>
