<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

$this->headTitle('advert_frontend_title_modify_edit');
$this->h1('advert_frontend_h1_modify_edit');
?>
<div class="well">
  In Kürze mehr...
</div>
