<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use UserModel\Entity\UserEntity;

/** @var UserEntity $user */
$user = $this->user;

$listLink    = $this->url('user-backend', [], true);
$showLink    = $this->url(
    'user-backend/show', ['id' => $user->getId()], true
);
$editLink    = $this->url(
    'user-backend/modify', ['action' => 'edit', 'id' => $user->getId()], true
);
$deleteLink  = $this->url(
    'user-backend/modify', ['action' => 'delete', 'id' => $user->getId()], true
);
$approveLink = $this->url(
    'user-backend/modify', ['action' => 'approve', 'id' => $user->getId()], true
);
$blockLink   = $this->url(
    'user-backend/modify', ['action' => 'block', 'id' => $user->getId()], true
);

$this->headTitle('user_backend_title_display_block');
$this->h1('user_backend_h1_display_block');
?>
<div class="alert alert-danger">
  <p>
    <strong>
      <?= $this->translate('user_backend_message_block_user') ?>
    </strong>
  </p>
  <p>
    <a class="btn btn-danger"
       href="<?= $blockLink ?>?block=yes">
      <?= $this->translate('user_backend_action_block') ?>
    </a>
    <a class="btn btn-default" href="<?= $showLink ?>">
      <?= $this->translate('user_backend_action_cancel') ?>
    </a>
  </p>
</div>
<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('user_backend_action_show_short') ?>
    </span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-default">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('user_backend_action_edit_short') ?>
    </span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('user_backend_action_delete_short') ?>
    </span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('user_backend_action_approve_short') ?>
    </span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-primary">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('user_backend_action_block_short') ?>
    </span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('user_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well" style="position: relative">
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('user_backend_label_registered') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->dateFormat(
            $user->getRegistered(),
            IntlDateFormatter::MEDIUM,
            IntlDateFormatter::MEDIUM
        ) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('user_backend_label_updated') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->dateFormat(
            $user->getUpdated(),
            IntlDateFormatter::MEDIUM,
            IntlDateFormatter::MEDIUM
        ) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('user_backend_label_status') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->translate(
            'user_model_option_status_' . $user->getStatus()
        ) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('user_backend_label_role') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->translate(
            'user_model_option_role_' . $user->getRole()
        ) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('user_backend_label_email') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $user->getEmail() ?>
      </div>
    </div>
  </form>
</div>

