<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
?>
<footer id="footer">
  <div class="footer-top"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <h4>
          <?= $this->translate('application_h4_footer_skeleton'); ?>
        </h4>
        <p>
          <?= $this->translate('application_message_footer_skeleton'); ?>
        </p>
      </div>
      <div class="col-lg-4">
        <h4>
          <?= $this->translate('application_h4_footer_links1'); ?>
        </h4>
        <ul>
          <li>
            <a href="http://framework.zend.com/" target="_blank">
              <?= $this->translate('application_label_zfwebsite'); ?>
            </a>
          </li>
          <li>
            <a href="http://modules.zendframework.com/" target="_blank">
              <?= $this->translate('application_label_zfmodules'); ?>
            </a>
          </li>
          <li>
            <a href="https://github.com/zendframework/" target="_blank">
              <?= $this->translate('application_label_zfgithub'); ?>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-lg-4">
        <h4>
          <?= $this->translate('application_h4_footer_links2'); ?>
        </h4>
        <ul>
          <li>
            <a href="http://www.zendframeworkbuch.de/" target="_blank">
              <?= $this->translate('application_label_zf3buch'); ?>
            </a>
          </li>
          <li>
            <a href="https://github.com/zf3buch/zendframework-center"
               target="_blank">
              <?= $this->translate('application_label_zf3buch_skeleton'); ?>
            </a>
          </li>
          <li>
            <a href="http://www.ralfeggert.de" target="_blank">
              <?= $this->translate('application_label_ralfeggert'); ?>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
