<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use Zend\View\Helper\Navigation\Menu;

?>
<div class="container">
  <header>
    <div class="row">
      <div class="col-sm-4">
        <a href="<?= $this->url('home', [], true); ?>">
          <img src="/assets/custom/img/logo.png" class="logo">
        </a>
      </div>
      <div class="col-sm-8">
        <?php echo $this->userShowUserWidget(); ?>
      </div>
    </div>
  </header>
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">
          <?= $this->translate('application_misc_toggle_navigation'); ?>
        </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <?php
      /** @var Menu $menuHelper */
      $menuHelper = $this->navigation('navigation')->menu();
      $menuHelper->setUlClass('nav navbar-nav');

      echo $menuHelper->render();
      ?>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="<?= $this->url(null, ['lang' => 'de'], true) ?>">
            <?= $this->translate('application_navigation_german'); ?>
          </a>
        </li>
        <li>
          <a href="<?= $this->url(null, ['lang' => 'en'], true) ?>">
            <?= $this->translate('application_navigation_english'); ?>
          </a>
        </li>
      </ul>
    </div>
  </nav>
</div>
