<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertBackend\Form\AdvertFormInterface;

/** @var AdvertFormInterface $form */
$form = $this->advertForm;

$listLink = $this->url('advert-backend', [], true);

$this->headTitle('advert_backend_title_display_add');
$this->h1('advert_backend_h1_display_add');

$this->inlineScript()->prependFile(
    '/assets/vendor/ckeditor/ckeditor.js', 'text/javascript'
);
$this->inlineScript()->appendScript('CKEDITOR.replace("advert_text");');
?>
<p>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well">
  <?= $this->bootstrapForm($form); ?>
</div>
