<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertModel\Entity\AdvertEntity;

/** @var AdvertEntity $advert */
$advert = $this->advert;

if ($advert->getType() == 'job') {
  $advertType = 'Job';
} else {
  $advertType = 'Projekt';
}

$listLink    = $this->url('advert-backend', [], true);
$showLink    = $this->url(
    'advert-backend/show', ['id' => $advert->getId()], true
);
$editLink    = $this->url(
    'advert-backend/modify', ['action' => 'edit', 'id' => $advert->getId()], true
);
$deleteLink  = $this->url(
    'advert-backend/modify', ['action' => 'delete', 'id' => $advert->getId()], true
);
$approveLink = $this->url(
    'advert-backend/modify', ['action' => 'approve', 'id' => $advert->getId()], true
);
$blockLink   = $this->url(
    'advert-backend/modify', ['action' => 'block', 'id' => $advert->getId()], true
);

$this->headTitle('Annonce sperren');
?>
<div class="page-header">
  <h1>Annonce sperren</h1>
</div>

<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">Anzeigen</span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-default">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">Bearbeiten</span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">Löschen</span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">Freigeben</span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-primary">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">Sperren</span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">Übersicht</span>
  </a>
</p>
<div class="alert alert-danger">
  <p>
    <strong>Möchten Sie diese Annonce sperren?</strong>
  </p>
  <p>
    <a class="btn btn-danger"
       href="<?= $blockLink ?>?block=yes">
      Annonce sperren
    </a>
    <a class="btn btn-default" href="<?= $showLink ?>">
      Abbrechen
    </a>
  </p>
</div>
<div class="well">
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">Typ</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getType() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Angelegt</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getCreated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Geändert</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getUpdated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Status</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getStatus() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Unternehmen</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getCompany()->getName() ?>
        <i>
          (Ansprechpartner:
          <?= $advert->getCompany()->getContact() ?>,
          E-Mail-Adresse:
          <?= $advert->getCompany()->getEmail() ?>)
        </i>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Ort</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getLocation() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Titel</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getTitle() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Text</label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getText() ?>
      </div>
    </div>
  </form>
</div>
