<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertModel\Entity\AdvertEntity;

/** @var AdvertEntity $advert */
$advert = $this->advert;

$listLink    = $this->url('advert-backend', [], true);
$showLink    = $this->url(
    'advert-backend/show', ['id' => $advert->getId()], true
);
$editLink    = $this->url(
    'advert-backend/modify', ['action' => 'edit', 'id' => $advert->getId()], true
);
$deleteLink  = $this->url(
    'advert-backend/modify', ['action' => 'delete', 'id' => $advert->getId()], true
);
$approveLink = $this->url(
    'advert-backend/modify', ['action' => 'approve', 'id' => $advert->getId()], true
);
$blockLink   = $this->url(
    'advert-backend/modify', ['action' => 'block', 'id' => $advert->getId()], true
);

$this->headTitle('advert_backend_title_display_block');
$this->h1('advert_backend_h1_display_block');
?>
<div class="alert alert-danger">
  <p>
    <strong>
      <?= $this->translate('advert_backend_message_block_advert') ?>
    </strong>
  </p>
  <p>
    <a class="btn btn-danger"
       href="<?= $blockLink ?>?block=yes">
      <?= $this->translate('advert_backend_action_block') ?>
    </a>
    <a class="btn btn-default" href="<?= $showLink ?>">
      <?= $this->translate('advert_backend_action_cancel') ?>
    </a>
  </p>
</div>
<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_show_short') ?>
    </span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-default">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_edit_short') ?>
    </span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_delete_short') ?>
    </span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_approve_short') ?>
    </span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-primary">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_block_short') ?>
    </span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_overview') ?>
    </span>
  </a>
</p>
<div class="well">
  <form class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_type') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->translate('advert_model_option_type_' . $advert->getType()) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_created') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getCreated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_updated') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getUpdated()->format('d.m.Y H:i:s') ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_status') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $this->translate(
            'advert_model_option_status_' . $advert->getStatus()
        ) ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_company') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getCompany()->getName() ?>
        <i>
          (<?= $this->translate('advert_frontend_label_type_contact') ?>:
          <?= $advert->getCompany()->getContact() ?>,
          <?= $this->translate('company_backend_label_email') ?>:
          <?= $advert->getCompany()->getEmail() ?>)
        </i>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_location') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getLocation() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_title') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getTitle() ?>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">
        <?= $this->translate('advert_backend_label_text') ?>
      </label>
      <div class="col-sm-10 form-control-static">
        <?= $advert->getText() ?>
      </div>
    </div>
  </form>
</div>
