<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertBackend\Form\AdvertFormInterface;
use AdvertModel\Entity\AdvertEntity;

/** @var AdvertFormInterface $form */
$form = $this->advertForm;

/** @var AdvertEntity $advert */
$advert = $this->advert;

$listLink    = $this->url('advert-backend', [], true);
$showLink    = $this->url(
    'advert-backend/show', ['id' => $advert->getId()], true
);
$editLink    = $this->url(
    'advert-backend/modify', ['action' => 'edit', 'id' => $advert->getId()], true
);
$deleteLink  = $this->url(
    'advert-backend/modify', ['action' => 'delete', 'id' => $advert->getId()], true
);
$approveLink = $this->url(
    'advert-backend/modify', ['action' => 'approve', 'id' => $advert->getId()], true
);
$blockLink   = $this->url(
    'advert-backend/modify', ['action' => 'block', 'id' => $advert->getId()], true
);

$this->headTitle('advert_backend_title_display_edit');
$this->h1('advert_backend_h1_display_edit');

$this->inlineScript()->prependFile(
    '/assets/vendor/ckeditor/ckeditor.js', 'text/javascript'
);
$this->inlineScript()->appendScript('CKEDITOR.replace("advert_text");');
?>
<p>
  <a href="<?= $showLink ?>" class="btn btn-default">
    <i class="fa fa-file-text-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_show_short') ?>
    </span>
  </a>
  <a href="<?= $editLink ?>" class="btn btn-primary">
    <i class="fa fa-pencil"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_edit_short') ?>
    </span>
  </a>
  <a href="<?= $deleteLink ?>" class="btn btn-default">
    <i class="fa fa-trash-o"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_delete_short') ?>
    </span>
  </a>
  <a href="<?= $approveLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-up"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_approve_short') ?>
    </span>
  </a>
  <a href="<?= $blockLink ?>" class="btn btn-default">
    <i class="fa fa-thumbs-o-down"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_block_short') ?>
    </span>
  </a>
  <a href="<?= $listLink ?>" class="btn btn-default">
    <i class="fa fa-list"></i>
    <span class="hidden-xs hidden-sm">
      <?= $this->translate('advert_backend_action_overview') ?>
    </span>
  </a>
</p>
<?php
$staticElements = [
    [
        'label' => 'Typ',
        'value' => $advert->getType(),
    ],
    [
        'label' => 'Angelegt',
        'value' => $advert->getCreated()->format('d.m.Y H:i:s'),
    ],
    [
        'label' => 'Geändert',
        'value' => $advert->getUpdated()->format('d.m.Y H:i:s'),
    ],
    [
        'label' => 'Status',
        'value' => $advert->getStatus(),
    ],
    [
        'label' => 'Unternehmen',
        'value' => $advert->getCompany()->getName()
            . ' <i>(Ansprechpartner: '
            . $advert->getCompany()->getContact()
            . ' E-Mail-Adresse: '
            . $advert->getCompany()->getEmail() . ')</i>',
    ],
];
?>
<div class="well">
  <?= $this->bootstrapForm($form, $staticElements); ?>
</div>
