<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use UserModel\Entity\UserEntity;

/** @var UserEntity $identity */
$identity = $this->identity;
?>
<?php if (!$identity) : ?>
  <?= $this->userShowLoginForm('form-inline'); ?>
<?php else: ?>
  <?= $this->userShowLogoutForm('form-inline'); ?>
  <div class="form-inline text-right">
    <div class="form-control">
      <p><?= $identity->getEmail() ?></p>
    </div>
    &nbsp;
  </div>
<?php endif; ?>
