<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'company-backend/display/show'   => __DIR__ . '/view/company-backend/display/show.phtml',
    'company-backend/display/index'  => __DIR__ . '/view/company-backend/display/index.phtml',
    'company-backend/modify/block'   => __DIR__ . '/view/company-backend/modify/block.phtml',
    'company-backend/modify/approve' => __DIR__ . '/view/company-backend/modify/approve.phtml',
    'company-backend/modify/add'     => __DIR__ . '/view/company-backend/modify/add.phtml',
    'company-backend/modify/delete'  => __DIR__ . '/view/company-backend/modify/delete.phtml',
    'company-backend/modify/edit'    => __DIR__ . '/view/company-backend/modify/edit.phtml',
);
