<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'advert-frontend/display/detail' => __DIR__ . '/view/advert-frontend/display/detail.phtml',
    'advert-frontend/display/index'  => __DIR__ . '/view/advert-frontend/display/index.phtml',
);
