<?php
/**
 * ZF3 book Zend Framework Center Example Application
 *
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/zendframework-center
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */

use AdvertModel\Entity\AdvertEntity;

/** @var AdvertEntity $job */
$job     = $this->randomJob;

/** @var AdvertEntity $project */
$project = $this->randomProject;

$jobText = strip_tags($job->getText());
$jobText = implode(
    ' ', array_slice(explode(' ', $jobText), 0, 50)
);

$projectText = strip_tags($project->getText());
$projectText = implode(
    ' ', array_slice(explode(' ', $projectText), 0, 50)
);

$jobDetailLink = $this->url('advert-job/detail', ['id' => $job->getId()], true);

$projectDetailLink = $this->url(
    'advert-project/detail', ['id' => $project->getId()], true
);

$jobListLink = $this->url('advert-job', [], true);

$projectListLink = $this->url('advert-project', [], true);
?>
<div class="page-header">
  <h1>Willkommen zum Zend Framework Center!</h1>
</div>

<div class="row">
  <div class="col-sm-6">
    <h2>
      <a href="<?= $jobListLink; ?>">Jobs</a>
    </h2>

    <div class="panel panel-primary">
      <div class="panel-heading clearfix">
        <strong>
          <a href="<?= $jobDetailLink; ?>"><?= $job->getTitle(); ?></a>
        </strong>
      </div>
      <div class="panel-body">
        <p>
          <img src="<?= $job->getCompany()->getLogo() ?>"
               class="img-responsive center-block">
        </p>
        <p><?= $jobText; ?> ...</p>
        <p class="text-center">
          <a href="<?= $jobDetailLink ?>" class="btn btn-primary">
            Job anzeigen
          </a>
        </p>
      </div>
      <div class="panel-footer clearfix">
        <div class="left-text">
          <div class="label label-primary">
            Zend Framework Job in <?= $job->getLocation(); ?>
          </div>
        </div>
        <div class="right-text">
          <div class="label label-primary">
            Letzte Änderung: <?= $job->getUpdated()->format('Y-m-d H:i:s') ?>
          </div>
        </div>
      </div>
    </div>
    <p class="text-center">
      <a href="<?= $jobListLink; ?>" class="btn btn-primary">
        Alle Zend Framework Jobs anzeigen
      </a>
    </p>
  </div>
  <div class="col-sm-6">
    <h2>
      <a href="<?= $projectListLink; ?>">Projekte</a>
    </h2>

    <div class="panel panel-success">
      <div class="panel-heading clearfix">
        <strong>
          <a href="<?= $projectDetailLink; ?>">
            <?= $project->getTitle(); ?>
          </a>
        </strong>
      </div>
      <div class="panel-body">
        <p>
          <img src="<?= $project->getCompany()->getLogo() ?>"
               class="img-responsive center-block">
        </p>
        <p><?= $projectText; ?> ...</p>
        <p class="text-center">
          <a href="<?= $projectDetailLink ?>" class="btn btn-success">
            Projekt anzeigen
          </a>
        </p>
      </div>
      <div class="panel-footer clearfix">
        <div class="left-text">
          <div class="label label-success">
            Zend Framework Job in <?= $project->getLocation(); ?>
          </div>
        </div>
        <div class="right-text">
          <div class="label label-success">
            Letzte Änderung: <?= $project->getUpdated()->format('Y-m-d H:i:s') ?>
          </div>
        </div>
      </div>
    </div>
    <p class="text-center">
      <a href="<?= $projectListLink; ?>" class="btn btn-success">
        Alle Zend Framework Projekte anzeigen
      </a>
    </p>
  </div>
</div>
